# include = ["*test.sql"]
# exclude = []
[lint]
# select = ["UN*", "GN*", "TYP*", "CST*"]
# select = ["GN*"]
# ignore = ["SM*"]
# include = ["test.sql", "new.sql"]
# exclude = ["*.py"]
# fix = false
# date_column_suffix = "_date"

# ignore-noqa = true

disallowed-schemas = [
    { name = "partitions", reason = "Deprecated", use-instead = "part" },
    # { name = "public", reason = "Default schema", use-instead = "amlex" },
]

disallowed-data-types = [
    { name = "point", reason = "Deprecated", use-instead = "text" },
]

# required-columns = [
#     { name = "created", data-type = "timestamptz" },
#     { name = "updated", data-type = "timestamptz" },
# ]

# exclude = ["*test.sql"]
# timestamp-column-suffix = "_at"
regex-partition = "[a-zA-Z0-9]+__[a-zA-Z0-9_]+__[a-zA-Z0-9_]+$"
regex-index = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_idx$"
regex-constraint-primary-key = "[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_pkey$"
regex-constraint-unique-key = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_key$"
regex-constraint-foreign-key = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_fkey$"
regex-constraint-check = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_check$"
regex-constraint-exclusion = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_exclusion$"
regex-sequence = "[a-zA-Z0-9].+_seq$"
extensions = []
languages = []

[format]
check = true
