[lint]
# select = ["UNS*"]
# ignore = ["CV*"]
# include = ["test.sql", "new.sql"]
ignore-noqa = false
disallowed-schemas = [
    { name = "partitions", reason = "Deprecated", use-instead = "part" },
    { name = "public", reason = "Default schema", use-instead = "amlex" },
]

disallowed-data-types = [
    { name = "point", reason = "Deprecated", use-instead = "text" },
]

required-columns = [
    { name = "created", data-type = "timestamptz" },
    { name = "updated", data-type = "timestamptz" },
]

# exclude = ["*test.sql"]
partition-strategies = ["hash", "list", "range"]
regex-constraint-check = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_check$"
extensions = []
languages = []
