[lint]
# select = ["UNS*"]
# ignore = ["CV*"]
schemas = ["partitions", "public"]
# exclude = ["*test.sql"]
partition_strategies = ["range"]
regex_constraint_check = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_check$"
