[lint]
# select = ["CVS002", "CVI003"]
ignore = ["CVI003"]
schemas = ["partitions", "public"]
partition_strategies = ["range"]
regex_constraint_check = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_chk$"
