[lint]
select = []
ignore = []
schemas = []
extensions = []
partition_strategies = []

required_columns = { created = "timestamptz", updated = "timestamptz" }

# schemas = { partition = "partitions", table = "public" } # improvements to whitelisting of schemas
# object_type: list of schemas

regex_partition = "[a-zA-Z0-9]+__[a-zA-Z0-9]+__[a-zA-Z0-9_]+$"
regex_index = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_idx$"
regex_constraint_primary_key = "[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_pkey$"
regex_constraint_unique_key = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_key$"
regex_constraint_foreign_key = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_fkey"
regex_constraint_check = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_check$"
regex_constraint_exclusion = "[a-zA-Z0-9]+_[a-zA-Z0-9]+(?:_[a-zA-Z0-9]+)*_exclusion$"
regex_sequence = "[a-zA-Z0-9].+_seq$"
