---
site_name: pgRubic
site_description:
  PostgreSQL linter for schema migrations and design best practices

repo_url: https://github.com/bolajiwahab/pgrubic
repo_name: pgrubic

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            # allow_inspection: false
            show_bases: false
            show_source: false
            # members: false
            # show_submodules: true
            show_labels: false
            inherited_members: true
            group_by_category: true
            # show_if_no_docstring: true
            # show_root_headings: true
            # show_root_toc_entry: true
            # show_signature_annotations: false
            # members:
            # - code
            # - name
            filters:
              - "!^_"
              - "!^__"
              - "!^visit"
              - "!^is_fix_applicable"
  - search
# - social

theme:
  name: material
  logo: ../assets/logo.png
  favicon: ../assets/logo.png
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  hide:
    - toc
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Overview: index.md
  - Tutorial: tutorial.md
  - Rules: rules.md

# not_in_nav: |
#   ./rules/unsafe/.*
#   ./rules/convention/.*
