---
site_name: pgrubic
site_description:
  PostgreSQL linter for schema migrations and design best practices

repo_url: https://github.com/bolajiwahab/pgrubic
repo_name: pgrubic

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [../src]
          options:
            show_bases: false
            show_source: false
            show_labels: false
            inherited_members: true
            group_by_category: true
            filters:
              - "!^_"
              - "!^__"
              - "!^visit"
              - "!^is_fix_applicable"
  - search

theme:
  name: material
  logo: ../assets/logo.png
  favicon: ../assets/logo.png
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  hide:
    - toc
  icon:
    repo: fontawesome/brands/git-alt
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: teal
      accent: blue

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: teal
      accent: blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Linter: linter.md
  - Formatter: formatter.md
  - Configuring pgrubic: configuration.md
  - Rules: rules.md

# not_in_nav: |
#   ./rules/unsafe/.*
#   ./rules/convention/.*
