---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jobs: [
          "linting",
          "isort",
          "formatting",
          "typing",
          "docbuild",
          "ensure-docs-up-to-date",
          "tests",
          "coverage-report",
        ]
    name: ${{ matrix.jobs }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install tox
      - name: Run ${{ matrix.jobs }}
        run: tox -e ${{ matrix.jobs }}
