---
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jobs: [
          "linting",
          "isort",
          "formatting",
          "typing",
          "docbuild",
          "tests",
          "coverage-report",
        ]
    name: ${{ matrix.jobs }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install tox
      - name: Run ${{ matrix.jobs }}
        run: tox -e ${{ matrix.jobs }}

  # tests:
  #   runs-on: ubuntu-latest
  #   name: tests
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #     - name: Install dependencies
  #       run: pip install tox
  #     - name: Run tests
  #       run: tox -e tests

  # coverage:
  #   runs-on: ubuntu-latest
  #   name: coverage
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.12"
  #     - name: Install dependencies
  #       run: pip install tox
  #     - name: Run coverage
  #       run: tox -e coverage-report
