---
name: "PR and Issue Labeler"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

  issues:
    types:
      - opened
      - edited
      - reopened

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.4
        with:
          configuration-path: .github/labeler.yml
          include-title: 1
          include-body: 0
          enable-versioned-regex: 0
          sync-labels: 1
          repo-token: ${{ github.token }}
